export const FILES_DATA = [
  {
    id: 1,
    name: "Work",
    type: "Folder",
    size: "3.9 MB",
    modified: "11 months ago",
    tags: [],
    shared: true,
  },
  {
    id: 2,
    name: "Virtual conference plan.whiteboard",
    type: "File",
    size: "22 KB",
    modified: "5 minutes ago",
    tags: [],
    shared: true,
  },
  {
    id: 3,
    name: "Last year keynote speakers.md",
    type: "File",
    size: "2 KB",
    modified: "5 days ago",
    tags: [],
    shared: false,
  },
  {
    id: 4,
    name: "Readme.md",
    type: "File",
    size: "< 1 KB",
    modified: "6 days ago",
    tags: [],
    shared: false,
  },
  {
    id: 5,
    name: "Report last year.odt",
    type: "File",
    size: "9 KB",
    modified: "6 days ago",
    tags: ["Aircraft", "Architecture"],
    shared: true,
  },
];
